### ISSUE TITLE
Website translations

### ISSUE THREAD

**Issue by Defnyddiwr** [rase-rocks/byw#31]
Hello.
I have recently visited the byw.cymru website and noticed that there is an option to view it in Spanish. I can speak fluent Spanish and would like to help improve the Spanish version of the website, although I don't have enough coding experience to manually edit websites, I would be happy to translate the text of the English website into Spanish.

**Comment by rase-rocks** [comment]
Hi, your contribution would be most welcome! No code is required to improve the translations for the website, once your changes are merged in, they will be included by the build system next time it is run, with the changes being visible on the production web page shortly after.

I see you have already taken the first step in the process in forking this repo. I'd recommend cloning your repo to your local machine. 

If you are unfamiliar with this there are plenty of tutorials on-line... but, assuming you have `git` installed on your local machine, just run

```sh
git clone 'name of your repo here (copied from the GitHub page for your repo)'
```

This will bring down all the resources you would need to work on any part of the site, but the part you will likely be most interested in is the `text` folder. If you poke around inside this folder you will see a subfolders for each of the currently supported languages. The name of the folder is important, as it is used by the build system to identify the language and translations contained within it.

Inside the folder you will find a `csv` file that contains all the info needed to create the translation for the site. It is a `csv` file so you can edit it in any text editor or even a spreadsheet if you prefer.

The `csv` file is structured with a `key`, this is what the system uses to choose which string to include on the page, a translator hint, which is an English language description of what the string refers to, and the translation itself.

Once you find and correct any errors, you can use `git` to push your changes back to GitHub.

```sh
git push origin master
```

Is something like the command you would use to do that. With `master` being the branch on your local system that contains the changes.

Once you have done that, successfully, you will see your changes, in your repo, on GitHub. After that, just create a pull request and your changes will be pulled into the main repo, unit tests run and if passing a new build of the website created and deployed shortly after. The unit tests check the translations (amongst other things) are structurally correct, not missing any keys and so on. They don't check the content of the translation.

Diolch a pob lwc i'chi!

**Comment by Defnyddiwr** [comment]
Hello again.
I have updated the Spanish website translation and pushed the excel spreadsheet I made the changes to it on, but I'm not sure how to create the pull request. Could you give me advice on how to do this?
Diolch yn fawr am helpu fi!

**Comment by rase-rocks** [comment]
Hi,

Thanks for your great work. In support of the changes requested in the Pull Request review I though it might be helpful to show an example of what is happening to cause the malformatting of your CSV file.

This is what the original `translation.csv` file looked like (top 3 lines):

```
key,translatorHint,value
pageTitleKeyHome, "Home", "Hogar"
pageTitleKeyMap, "Map", "Mapa"
```

There are a couple of things to call out in this. The first is the top line. That just describes what the rows below contain, and how they are laid out. This enables the build system to pick up the translation and make it available for presentation on the live website.

Next is that each field is delimited by a `,`. Using a comma means whenever the build system finds a comma it will consider that the end of one field and the start of the next. To enable the use of commas inside the presentation we wrap the sentence in `"`. As such it is important that the `"` are matched, in that if we start the field with a `"` we must match it at the end of the field. If we wanted to use the `"` character within the field, we would have to substitute it for another character that does not have meaning to the build system. For example a `'` character would be fine, as it is not reserved for use in structuring the data contained within the CSV file.

Then you will see that there are no trailing `,` at the end of the line. This is because the build system will treat the `\n` (end of line) character as the end of the row. (This also means the `\n` character is also reserved and should not be used within a field).

The CSV format is fairly loose in its definition, so this project uses a very simple convention. Which is, use `,` as the field delimiter, wrap fields in a single `"` character and have no trailing `,`. (The trailing `,` would indicate there are extra fields, which do not have labels, which makes no sense in this scenario).

Below is the first 3 lines after they have been manipulated by Excel. You can see the fields are wrapped by multiple `"`, which would cause the text to be presented to also contain the `"` and therefore be shown on screen. For most cases this is not what we are after. It also adds a lot of unlabeled fields before the new line character. Those fields are all empty and so, combined with the lack of label for the field have no meaning, and should therefore be omitted.

```
key,translatorHint,value,,,,,,,,,,,
pageTitleKeyHome," ""Home"""," ""Página principal""",,,,,,,,,,,
pageTitleKeyMap," ""Map"""," ""Mapa""",,,,,,,,,,,
```

Also, it appears that Excel is not set to use UTF8 string encoding, don't worry if this doesn't mean anything to you, just know that how strings (text) are encoded is important, because it the encodings are mixed, strange effects can occur.

I plucked this next example (of how string encoding matters) because it is short and shows the issue well.

Take a look:

```
aboutSub1," ""What can"""," ""QuÃ© puede""",,,,,,,,,,,
```

As you can see, the issues from above are present, but beyond that it contains the `Ã` character, which i'm sure is not correct in this context and the `©`, which definitely is not correct in this context (my Spanish is poor, but this symbol is not part of the alphabet!)

How to fix:

If I were to attempt to fix this I would start with a RegEx Find/Replace of multiple `"` characters.

Something like `"+\s?"+` (depending on the flavor of RegEx used by your text editor) will find all the errant (this particular example reads like find one or more `"` followed by zero of more `whitespace` followed by one or more `"`). It will match `" ""`, `"""` and `"" "`. Replacing with a single `"`.

Then a similar thing for the commas (match against more than one `,` and replace with a single `,`)

As for the string encoding issue, using a text editor set to use UTF8 will resolve that issue, but you may need to check each field for correctness to remove the artifacts Excel left behind.

If you prefer to use Excel, then I would suggest making sure that it is using UTF8 and adjust the CSV export settings so they match the expected result. Sorry I can't be of more help with that, but I have no experience with using Excel.

It would appear that Excel has thwarted your effort. A simpler way forward might be to consider using a plain text editor (such as Microsoft Visual Studio Code (not to be confused with a very different but similarly name product 'Visual Studio')). In VS Code you can paste the RegEx above straight into the Find/Replace box, check 'use regex' and it will do the job in a single click.

With VS Code you could also install an extension, such as `Rainbow CSV` which will highlight the fields in different colors which makes it very easy to spot CSV structural errors.

I hope this explanation helps!

**Comment by rase-rocks** [comment]
PR #33 accepted and merged. Cache invalidated. Changes now live.
